---
services:
  server:
    container_name: wid-server
    build: .
    ports:
      - "8080:8080"
  database:
    container_name: wid-database
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: whatitdoo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data