---
volumes:
  db_data:

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: whatitdoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data