---
volumes:
  db_data:

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: whatitdo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data