---
apiVersion: batch/v1
kind: Job
metadata:
  name: database-migrations
  namespace: what-it-doo
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: goose
        image: registry.gitlab.pycrs.cz/tul/what-it-doo/migrate
        env:
          - name: GOOSE_DRIVER
            value: "postgres"
          - name: GOOSE_DBSTRING
            valueFrom:
              secretKeyRef:
                name: wid-secrets
                key: WID_DATABASE_URL
      restartPolicy: Never
